# 配置文件

DAILY_TIME: "08:00" # 每日定时发送时间。该时间为系统时间，如果当前系统时间不为北京时间需要自行进行换算

START_DATE: "2022-04-08" # 纪念日
CITY: "石家庄"

BIRTHDAY:
  - "10-27"

APP_ID: "wx6e3692eac6b35de9"
APP_SECRET: "3df2000d073132820bef7376f070c270"

USER_ID:
  - "oW1X86sCUZaORQ89s75ADssHp6z8"
  - "oW1X86lnC4Qj72FqAlX25rejwtSk" # 你可以通过配置多个USER_ID来设置多个接受者，如果接受者只有一人删除本行即可
TEMPLATE_ID:
  - "orI9mK_b5uIQMLAjjXraPz_HESGL9Q3jZgpIQ3mv2Ww" # question
  - "bqScA3IHEdRcBqfuXZF1hn-idJX6NyuuhasDdv51cG4" # answer
  - "amXhoDJtncdHIr-QfRUGeFkFswmFKy_vCj2_sER9pqE" # hello

